version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: monthly
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: bootsnap
    versions:
    - 1.5.1
    - 1.6.0
  - dependency-name: rails
    versions:
    - 6.1.0
    - 6.1.1
  - dependency-name: webdrivers
    versions:
    - 4.4.2
    - 4.5.0
  - dependency-name: nokogiri
    versions:
    - 1.11.0
  - dependency-name: capybara
    versions:
    - 3.34.0
