services:
  - postgresql

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

language: ruby

cache: bundler

script:
  - bundle exec rails db:reset db:setup db:migrate RAILS_ENV=test
  - bundle exec rails test
